config/routes.rb
Mss::Application.routes.draw do
  root to: 'top#index'

  resources :users

  resources :events, shallow: true do
    resources :events_users, expect:[:index, :show]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :events_users
  has_many :users, :through => :events_users
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :set_events_user, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @attend = ['未回答', '出席', '欠席', '未定']
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_events_user
      @events_users = EventsUser.where(:event_id => params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :brief, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :brief, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brief, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:brief) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= event.brief %></td>
        <td><%= event.date %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>
<br><br>
<%= link_to 'TOPへ戻る', root_path %>
<br><br>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brief) %>:</strong></dt>
  <dd><%= @event.brief %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @event.date %></dd>
</dl>

<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Num</th>
      <th>user name</th>
      <th>Attend flg</th>
      <th>Comment</th>
      <th>登録日時</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events_users.each do |events_user| %>
      <tr>
        <td><%= "num" %></td>
        <td><%= events_user.user.name %></td>
        <td><%= @attend[events_user.attend_flg] %></td>
        <td><%= events_user.comment %></td>
        <td><%= events_user.updated_at %></td>
        <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_events_user_path(events_user), :class => 'btn' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        events_user_path(events_user),
                        :method => 'delete',
                        :data =>
                          { 
                            :confirm => 
                              t('.confirm', 
                                :default => t("helpers.links.confirm", 
                                              :default => 'Are you sure?'
                                             )
                               )
                          },
                        :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to '出欠登録をする', 
              new_event_events_user_path(@event),
              :class => 'btn btn-primary'  %>
  <br><br>

  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>